// This file is auto-generated by `oboe generate:types`.

import type { StoredFileData } from "@oboe/core";

export interface ContactsDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  email?: string;
  company?: string | CompaniesDocument;
  owner?: string;
}

export interface ContactsInput {
  name: string;
  email?: string;
  company?: string | CompaniesDocument;
  owner?: string;
}

export type ContactsUpdateInput = Partial<ContactsInput>;

export interface CompaniesDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  domain?: string;
}

export interface CompaniesInput {
  name: string;
  domain?: string;
}

export type CompaniesUpdateInput = Partial<CompaniesInput>;

export interface DealsDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  stage?: "lead" | "qualified" | "proposal" | "won";
  owner?: string;
  value?: number;
  company?: string | CompaniesDocument;
}

export interface DealsInput {
  name: string;
  stage?: "lead" | "qualified" | "proposal" | "won";
  owner?: string;
  value?: number;
  company?: string | CompaniesDocument;
}

export type DealsUpdateInput = Partial<DealsInput>;

export interface ActivitiesDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  type?: string;
  summary?: string;
  contactId?: string | ContactsDocument;
}

export interface ActivitiesInput {
  type?: string;
  summary?: string;
  contactId?: string | ContactsDocument;
}

export type ActivitiesUpdateInput = Partial<ActivitiesInput>;

export interface MediaDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  title?: string;
  alt?: string;
  file?: StoredFileData;
}

export interface MediaInput {
  title?: string;
  alt?: string;
}

export type MediaUpdateInput = Partial<MediaInput>;

export interface UsersDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  email: string;
  role?: string;
}

export interface UsersInput {
  email: string;
  role?: string;
}

export type UsersUpdateInput = Partial<UsersInput>;

export interface FormsDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  slug: string;
  title: string;
  status: "draft" | "published";
  submitButtonLabel?: string;
  confirmationType: "message" | "redirect";
  confirmationMessage?: string;
  redirectURL?: string;
  fields: unknown;
  emails?: unknown;
}

export interface FormsInput {
  slug: string;
  title: string;
  status: "draft" | "published";
  submitButtonLabel?: string;
  confirmationType: "message" | "redirect";
  confirmationMessage?: string;
  redirectURL?: string;
  fields: unknown;
  emails?: unknown;
}

export type FormsUpdateInput = Partial<FormsInput>;

export interface FormSubmissionsDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  form: string | FormsDocument;
  submissionData: unknown;
}

export interface FormSubmissionsInput {
  form: string | FormsDocument;
  submissionData: unknown;
}

export type FormSubmissionsUpdateInput = Partial<FormSubmissionsInput>;

export interface Collections {
  contacts: ContactsDocument;
  companies: CompaniesDocument;
  deals: DealsDocument;
  activities: ActivitiesDocument;
  media: MediaDocument;
  users: UsersDocument;
  forms: FormsDocument;
  "form-submissions": FormSubmissionsDocument;
}

export interface CollectionInputs {
  contacts: ContactsInput;
  companies: CompaniesInput;
  deals: DealsInput;
  activities: ActivitiesInput;
  media: MediaInput;
  users: UsersInput;
  forms: FormsInput;
  "form-submissions": FormSubmissionsInput;
}

export type Globals = Record<string, never>;

export type GlobalInputs = Record<string, never>;

export type TaskInputs = Record<string, never>;

export type TaskOutputs = Record<string, never>;

declare module "@oboe/core" {
  interface GeneratedTypes {
    collections: Collections;
    collectionInputs: CollectionInputs;
    globals: Globals;
    globalInputs: GlobalInputs;
    taskInputs: TaskInputs;
    taskOutputs: TaskOutputs;
  }
}
