// This file is auto-generated by `oboe generate:types`.

import type { StoredFileData } from "@oboe/core";

export interface ContactsDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  email?: string;
  company?: string | CompaniesDocument;
  owner?: string;
}

export interface ContactsInput {
  name: string;
  email?: string;
  company?: string | CompaniesDocument;
  owner?: string;
}

export type ContactsUpdateInput = Partial<ContactsInput>;

export interface CompaniesDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  domain?: string;
}

export interface CompaniesInput {
  name: string;
  domain?: string;
}

export type CompaniesUpdateInput = Partial<CompaniesInput>;

export interface DealsDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  stage?: "lead" | "qualified" | "proposal" | "won";
  owner?: string;
  value?: number;
  company?: string | CompaniesDocument;
}

export interface DealsInput {
  name: string;
  stage?: "lead" | "qualified" | "proposal" | "won";
  owner?: string;
  value?: number;
  company?: string | CompaniesDocument;
}

export type DealsUpdateInput = Partial<DealsInput>;

export interface ActivitiesDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  type?: string;
  summary?: string;
  contactId?: string | ContactsDocument;
}

export interface ActivitiesInput {
  type?: string;
  summary?: string;
  contactId?: string | ContactsDocument;
}

export type ActivitiesUpdateInput = Partial<ActivitiesInput>;

export interface MediaDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  title?: string;
  alt?: string;
  file?: StoredFileData;
}

export interface MediaInput {
  title?: string;
  alt?: string;
}

export type MediaUpdateInput = Partial<MediaInput>;

export interface UsersDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
  email: string;
  role?: string;
}

export interface UsersInput {
  email: string;
  role?: string;
}

export type UsersUpdateInput = Partial<UsersInput>;

export interface Collections {
  contacts: ContactsDocument;
  companies: CompaniesDocument;
  deals: DealsDocument;
  activities: ActivitiesDocument;
  media: MediaDocument;
  users: UsersDocument;
}

export interface CollectionInputs {
  contacts: ContactsInput;
  companies: CompaniesInput;
  deals: DealsInput;
  activities: ActivitiesInput;
  media: MediaInput;
  users: UsersInput;
}

export type Globals = Record<string, never>;

export type GlobalInputs = Record<string, never>;

declare module "@oboe/core" {
  interface GeneratedTypes {
    collections: Collections;
    collectionInputs: CollectionInputs;
    globals: Globals;
    globalInputs: GlobalInputs;
  }
}
